version: '3.8'

services:
  agilent-support-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # Backend API
      - "3000:3000"  # Frontend
    volumes:
      - ./logs:/app/logs
      - ./feedback_data:/app/feedback_data
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/feedback

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=feedback
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
